# Generated by Django 4.2.8 on 2024-09-25 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="fpl_id",
        ),
    ]
