# Generated by Django 4.2.8 on 2024-09-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_remove_profile_fpl_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="team_name",
            field=models.CharField(max_length=100, verbose_name="Team Name"),
        ),
    ]
