services:
  api:
    build:
      context: .
      dockerfile: ./docker/production/django/Dockerfile
    container_name: api
    command: /start
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    env_file:
      - .env.prod
    depends_on:
      - postgres-db
      - redis
    networks:
      - fpl-vue

  postgres-db:
    image: postgres:12.0-alpine
    ports:
      - "5432:5432"
    container_name: postgres-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - fpl-vue

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - fpl-vue

  nginx:
    restart: always
    container_name: nginx
    depends_on:
      - api
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
      - ./docker/production/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      
    build:
      context: ./client  
      dockerfile: ./production/Dockerfile 
    ports:
      - "80:80"
      - "443:443"
    networks:
      - fpl-vue

  celery_worker:
    build:
      context: .
      dockerfile: ./docker/production/django/Dockerfile
    command: /start-celeryworker
    container_name: worker
    volumes:
      - .:/app
    env_file:
      - .env.prod
    depends_on:
      - redis
      - postgres-db
    networks:
      - fpl-vue

  celery_beat:
    build:
      context: .
      dockerfile: ./docker/production/django/Dockerfile
    container_name: beat
    command: /start-celerybeat
    volumes:
      - .:/app
    env_file:
      - .env.prod
    depends_on:
      - redis
      - postgres-db
    networks:
      - fpl-vue

  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium
    shm_size: 2gb
    ports:
      - "4444:4444"
      - "7900:7900"
    environment:
      - SE_NODE_SESSION_TIMEOUT=60
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    networks:
      - fpl-vue

networks:
  fpl-vue:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume: