"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import logging
import logging.config
import os
import re
from datetime import timedelta
from pathlib import Path

from celery.schedules import crontab
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/


def env(name, default=None):
    """os.getenv, but tolerant of stray whitespace around values.

    docker-compose's env_file keeps values verbatim, so a trailing space on a
    line makes its way into the value and breaks things far from the cause
    (e.g. a Google client_id arriving as "...googleusercontent.com%20").
    """
    value = os.getenv(name, default)
    return value.strip() if isinstance(value, str) else value


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG", "false").lower() == "true"

# Feature flags
LINEUPS_SCRAPING_ENABLED = env("LINEUPS_SCRAPING_ENABLED", "false").lower() == "true"
PRIMARY_LINEUP_SOURCE = env("PRIMARY_LINEUP_SOURCE", "fkf")
SELENIUM_REMOTE_URL = os.getenv("SELENIUM_REMOTE_URL", "http://selenium:4444/wd/hub")
LINEUP_SCRAPER_MAX_CONCURRENCY = int(env("LINEUP_SCRAPER_MAX_CONCURRENCY", "2"))
SCRAPER_USER_AGENT = os.getenv(
    "SCRAPER_USER_AGENT", "kenyan-fantasy-league/lineups-scraper"
)

ALLOWED_HOSTS = [
    h.strip() for h in re.split(r"[,\s]+", env("ALLOWED_HOSTS", "*")) if h.strip()
]

CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:8080",
    "http://0.0.0.0:8080",
    "http://localhost:8080",
    "http://api:8000",
    "http://nginx:80",
    "http://[::1]:8080",
    "https://fantasykenya.com",
    "https://www.fantasykenya.com",
]


SITE_ID = 1

DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
]

THIRD_PARTY_APPS = [
    "rest_framework",
    "django_countries",
    "phonenumber_field",
    "django_filters",
    "djoser",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",  # For token rotation security
    "djcelery_email",
    "django_celery_beat",
]

LOCAL_APPS = [
    "apps.accounts",
    "apps.profiles",
    "apps.kpl",
    "apps.fantasy",
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Africa/Nairobi"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/staticfiles/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIR = []

MEDIA_URL = "/mediafiles/"
MEDIA_ROOT = BASE_DIR / "mediafiles"
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "accounts.User"


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication"
    ],
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
    "DEFAULT_THROTTLE_CLASSES": ("rest_framework.throttling.UserRateThrottle",),
    "DEFAULT_THROTTLE_RATES": {
        "anon": "10/minute",
        "user": "1000/min",
        "premium": "12/minute",
    },
}


SIMPLE_JWT = {
    "AUTH_HEADERS_TYPES": ("Bearer", "JWT"),
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "SIGNING_KEY": env("SIGNING_KEY"),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "UPDATE_LAST_LOGIN": True,
}


# DJOSER = {
#     "LOGIN_FIELD": "email",
#     "USER_CREATE_PASSWORD_RETYPE": True,
#     "USERNAME_CHANGED_EMAIL_CONFIRMATION": True,
#     "PASSWORD_CHANGED_EMAIL_CONFIRMATION": True,
#     "SEND_CONFIRMATION_EMAIL": True,
#     "PASSWORD_RESET_CONFIRM_URL": "password/reset/confirm/{uid}/{token}",
#     "SET_PASSWORD_RETYPE": True,
#     "PASSWORD_RESET_CONFIRM_RETYPE": True,
#     "USERNAME_RESET_CONFIRM_URL": "email/reset/confirm/{uid}/{token}",
#     "ACTIVATION_URL": "activate/{uid}/{token}",
#     "SEND_ACTIVATION_EMAIL": True,
#     "SERIALIZERS": {
#         "user_create": "apps.accounts.serializers.UserCreateSerializer,",
#         "user": "apps.accounts.serializers.UserSerializer",
#         "current_user": "apps.accounts.serializers.UserSerializer",
#         "user_delete": "djoser.serializers.UserDeleteSerializer",
#     },
# }

DJOSER = {
    "LOGIN_FIELD": "email",
    "USER_CREATE_PASSWORD_RETYPE": True,
    "SET_PASSWORD_RETYPE": True,
    "SEND_ACTIVATION_EMAIL": False,
    "SEND_CONFIRMATION_EMAIL": False,
    "SERIALIZERS": {
        "user_create": "apps.accounts.serializers.UserCreateSerializer",
        "user": "apps.accounts.serializers.UserSerializer",
        "current_user": "apps.accounts.serializers.UserSerializer",
    },
}

logger = logging.getLogger(__name__)

LOG_LEVEL = "INFO"

LOG_DIR = BASE_DIR / "logs"
os.makedirs(LOG_DIR, exist_ok=True)
filename = LOG_DIR / "fantasy_league.log"

DEFAULT_LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "console": {
            "format": "%(asctime)s [%(levelname)s] %(name)s: %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
        "file": {
            "format": "%(asctime)s [%(levelname)s] %(name)s.%(funcName)s:%(lineno)d - %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
        "celery": {
            "format": "%(asctime)s [%(levelname)s] [%(task_name)s(%(task_id)s)] %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "console",
            "level": "INFO",
        },
        "file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "formatter": "file",
            "filename": LOG_DIR / "fantasy_league.log",
            "maxBytes": 30485760,
            "backupCount": 5,
        },
        "celery_file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "formatter": "celery",
            "filename": LOG_DIR / "celery.log",
            "maxBytes": 30485760,
            "backupCount": 5,
        },
        "celery_console": {
            "class": "logging.StreamHandler",
            "formatter": "celery",
            "level": "INFO",
        },
    },
    "loggers": {
        # Root logger - catches everything
        "": {
            "level": "INFO",
            "handlers": ["console", "file"],
            "propagate": False,
        },
        # Your app loggers
        "apps": {
            "level": "INFO",
            "handlers": ["console", "file"],
            "propagate": False,
        },
        "apps.kpl": {
            "level": "INFO",
            "handlers": ["console", "file"],
            "propagate": False,
        },
        "apps.fantasy": {
            "level": "INFO",
            "handlers": ["console", "file"],
            "propagate": False,
        },
        # Celery loggers - THIS IS CRITICAL
        "celery": {
            "handlers": ["celery_console", "celery_file"],
            "level": "INFO",
            "propagate": False,
        },
        "celery.worker": {
            "handlers": ["celery_console", "celery_file"],
            "level": "INFO",
            "propagate": False,
        },
        "celery.task": {
            "handlers": ["celery_console", "celery_file"],
            "level": "INFO",
            "propagate": False,
        },
        "celery.beat": {
            "handlers": ["celery_console", "celery_file"],
            "level": "INFO",
            "propagate": False,
        },
        # Reduce noise from these
        "flower": {
            "handlers": [],
            "level": "WARNING",
            "propagate": False,
        },
        "kombu": {
            "handlers": [],
            "level": "WARNING",
            "propagate": False,
        },
        "amqp": {
            "handlers": [],
            "level": "WARNING",
            "propagate": False,
        },
    },
}


CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

# ---------------------------------------------------------------------------
# Celery worker hardening
#
# The scraping tasks are long, network-bound and hit small third-party hosts.
# These settings stop one slow scrape from taking a worker down with it.
# ---------------------------------------------------------------------------

# Schedules below are written in Kenyan local time, which is also how the
# upstream sources publish kick-off times.
CELERY_TIMEZONE = "Africa/Nairobi"
CELERY_ENABLE_UTC = True

# Fetch one task at a time. With the default prefetch a worker grabs a batch of
# jobs up front, so a slow scrape leaves its queued siblings idle behind it
# while other workers sit empty.
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

# Acknowledge only after the task finishes, so a redeploy or an OOM kill
# redelivers the job instead of dropping it.
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True

# Chrome and lxml both leak across long-lived processes; recycling the child
# after a fixed number of tasks keeps worker memory flat.
CELERY_WORKER_MAX_TASKS_PER_CHILD = 40
CELERY_WORKER_MAX_MEMORY_PER_CHILD = 400_000  # KiB

# Global ceiling. Individual tasks set their own tighter limits.
CELERY_TASK_SOFT_TIME_LIMIT = 10 * 60
CELERY_TASK_TIME_LIMIT = 12 * 60

CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_TRANSPORT_OPTIONS = {"visibility_timeout": 15 * 60}
CELERY_RESULT_EXPIRES = 60 * 60 * 24 * 3
CELERY_TASK_TRACK_STARTED = True
CELERY_WORKER_SEND_TASK_EVENTS = True

# Scraping runs on its own queue so a stuck scrape cannot starve interactive
# work (emails, fantasy point recalculation) of worker slots.
CELERY_TASK_DEFAULT_QUEUE = "celery"
# CELERY_TASK_ROUTES is set further down, behind CELERY_SCRAPING_QUEUE_ENABLED.


CELERY_BEAT_SCHEDULE = {
    # --- squad and club metadata: changes rarely, checked weekly ---
    "sync-teams": {
        "task": "apps.kpl.tasks.sync.sync_teams",
        "schedule": crontab(day_of_week=1, hour=2, minute=0),
    },
    "sync-team-logos": {
        "task": "apps.kpl.tasks.sync.sync_team_logos",
        "schedule": crontab(day_of_week=1, hour=2, minute=20),
    },
    # --- calendar and squads: transfers and rescheduling, checked nightly ---
    "sync-fixtures": {
        "task": "apps.kpl.tasks.sync.sync_fixtures",
        "schedule": crontab(hour=3, minute=0),
    },
    "sync-players": {
        "task": "apps.kpl.tasks.sync.sync_players",
        "schedule": crontab(hour=3, minute=30),
    },
    # --- match data: matches kick off Fri-Sun afternoons, so poll through the
    #     evening rather than round the clock ---
    "sync-results": {
        "task": "apps.kpl.tasks.sync.sync_results",
        "schedule": crontab(hour="15-23/2", minute=10),
    },
    "sync-match-details": {
        "task": "apps.kpl.tasks.sync.sync_match_details",
        "schedule": crontab(hour="16-23/2", minute=40),
    },
    "sync-standings": {
        "task": "apps.kpl.tasks.sync.sync_standings",
        "schedule": crontab(hour="*/6", minute=15),
    },
    "sync-top-scorers": {
        "task": "apps.kpl.tasks.sync.sync_top_scorers",
        "schedule": crontab(hour=23, minute=30),
    },
    # --- gameweek bookkeeping ---
    "update-kpl-gameweek": {
        "task": "apps.kpl.tasks.fixtures.update_active_gameweek",
        "schedule": crontab(hour=4, minute=0),
    },
}


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://redis:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}


GOOGLE_CLIENT_ID = env("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = env("GOOGLE_CLIENT_SECRET")
# KPL fixtures scraping source (SportPress "sp-event-blocks" table). Read through
# env() so stray whitespace in .env / .env.prod (passed verbatim by docker-compose
# env_file) cannot corrupt the URL; the celery worker must use this, not raw os.getenv.
# ---------------------------------------------------------------------------
# Data sources
#
# The scrapers take their hosts from the environment rather than embedding them
# in the source tree, so the repository never names where the data comes from
# and a source can be swapped without a code change. All of these live in the
# gitignored .env / .env.prod; .env.example carries placeholders only.
# ---------------------------------------------------------------------------

# Primary source: server-rendered pages covering the whole competition.
SCRAPER_PRIMARY_BASE_URL = env("SCRAPER_PRIMARY_BASE_URL", "")
# The competition label as the primary source writes it, used to pick the
# current season out of its index (e.g. "<Competition Name>").
SCRAPER_PRIMARY_COMPETITION = env("SCRAPER_PRIMARY_COMPETITION", "")

# Hostnames the lineup adapter recognises, as "provider=host,host" pairs.
SCRAPER_PROVIDER_HOSTS = env("SCRAPER_PROVIDER_HOSTS", "")

# Page paths on the primary source, as "role=path" pairs. See .env.example.
SCRAPER_PRIMARY_PATHS = env("SCRAPER_PRIMARY_PATHS", "")

# Lineup providers to try, in order.
SCRAPER_LINEUP_PROVIDERS = env("SCRAPER_LINEUP_PROVIDERS", "")

# Route scraping onto its own Celery queue. Leave false until the images have
# been rebuilt with the queue-aware start scripts, otherwise the routed tasks
# have no worker listening for them.
CELERY_SCRAPING_QUEUE_ENABLED = (
    env("CELERY_SCRAPING_QUEUE_ENABLED", "false").lower() == "true"
)
if CELERY_SCRAPING_QUEUE_ENABLED:
    CELERY_TASK_ROUTES = {
        "apps.kpl.tasks.sync.*": {"queue": "scraping"},
        "apps.kpl.tasks.lineups.*": {"queue": "scraping"},
        "apps.kpl.tasks.live_games.*": {"queue": "scraping"},
    }
else:
    CELERY_TASK_ROUTES = {}

BASE_BACKEND_URL = env("BASE_BACKEND_URL", "http://localhost:8080")
FRONTEND_URL = env("FRONTEND_URL", "http://localhost:8080")
