# Generated by Django 4.2.8 on 2025-04-05 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("kpl", "0006_gameweek_alter_player_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FantasyPlayer",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_points", models.PositiveIntegerField(default=0)),
                ("gameweek_points", models.PositiveIntegerField(default=0)),
                ("is_captain", models.BooleanField(default=False)),
                ("is_vice_captain", models.BooleanField(default=False)),
                ("is_starter", models.BooleanField(default=True)),
                ("purchase_price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("current_value", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                "verbose_name": "Fantasy Player",
                "verbose_name_plural": "Fantasy Players",
            },
        ),
        migrations.CreateModel(
            name="FantasyTeam",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "budget",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=6),
                ),
                ("gameweek", models.PositiveIntegerField(default=1)),
                (
                    "formation",
                    models.CharField(
                        choices=[
                            ("3-4-3", "3-4-3"),
                            ("3-5-2", "3-5-2"),
                            ("4-4-2", "4-4-2"),
                            ("4-3-3", "4-3-3"),
                            ("5-3-2", "5-3-2"),
                            ("5-4-1", "5-4-1"),
                        ],
                        default="3-4-3",
                        max_length=10,
                    ),
                ),
                ("free_transfers", models.PositiveIntegerField(default=1)),
                ("total_points", models.PositiveIntegerField(default=0)),
                ("overall_rank", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "transfer_budget",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fantasy_teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fantasy Team",
                "verbose_name_plural": "Fantasy Teams",
            },
        ),
        migrations.CreateModel(
            name="PlayerTransfer",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transfer_cost",
                    models.DecimalField(decimal_places=1, default=0, max_digits=4),
                ),
                (
                    "fantasy_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers",
                        to="fantasy.fantasyteam",
                    ),
                ),
                (
                    "gameweek",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="kpl.gameweek"
                    ),
                ),
                (
                    "player_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_in",
                        to="kpl.player",
                    ),
                ),
                (
                    "player_out",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_out",
                        to="kpl.player",
                    ),
                ),
            ],
            options={
                "verbose_name": "Player Transfer",
                "verbose_name_plural": "Player Transfers",
            },
        ),
        migrations.CreateModel(
            name="PlayerPerformance",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("yellow_cards", models.PositiveIntegerField(default=0)),
                ("red_cards", models.PositiveIntegerField(default=0)),
                ("goals_scored", models.PositiveIntegerField(default=0)),
                ("assists", models.PositiveIntegerField(default=0)),
                ("clean_sheets", models.PositiveIntegerField(default=0)),
                ("saves", models.PositiveIntegerField(default=0)),
                ("own_goals", models.PositiveIntegerField(default=0)),
                ("penalties_saved", models.PositiveIntegerField(default=0)),
                ("penalties_missed", models.PositiveIntegerField(default=0)),
                ("minutes_played", models.PositiveIntegerField(default=0)),
                (
                    "fantasy_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performances",
                        to="fantasy.fantasyplayer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Player Performance",
                "verbose_name_plural": "Players Performance",
            },
        ),
        migrations.AddField(
            model_name="fantasyplayer",
            name="fantasy_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players",
                to="fantasy.fantasyteam",
            ),
        ),
        migrations.AddField(
            model_name="fantasyplayer",
            name="gameweek",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fantasy_players",
                to="kpl.gameweek",
            ),
        ),
        migrations.AddField(
            model_name="fantasyplayer",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="kpl.player"
            ),
        ),
        migrations.CreateModel(
            name="FantasyLeague",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("start_gameweek", models.PositiveIntegerField()),
                ("end_gameweek", models.PositiveIntegerField()),
                (
                    "commissioner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teams",
                    models.ManyToManyField(
                        related_name="leagues", to="fantasy.fantasyteam"
                    ),
                ),
            ],
            options={
                "verbose_name": "League",
                "verbose_name_plural": "Leagues",
            },
        ),
    ]
