# Generated by Django 4.2.8 on 2025-05-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fantasyteam",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
