# Generated by Django 4.2.8 on 2025-07-02 10:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("kpl", "0010_team_jersey_image"),
        ("fantasy", "0002_alter_fantasyteam_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="playerperformance",
            options={
                "verbose_name": "Player Performance",
                "verbose_name_plural": "Player Performances",
            },
        ),
        migrations.RemoveField(
            model_name="fantasyteam",
            name="gameweek",
        ),
        migrations.AddField(
            model_name="fantasyplayer",
            name="gameweek_added",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players_added",
                to="kpl.gameweek",
            ),
        ),
        migrations.AddField(
            model_name="fantasyteam",
            name="current_gameweek",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_teams",
                to="kpl.gameweek",
            ),
        ),
        migrations.AddField(
            model_name="playerperformance",
            name="fantasy_points",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerperformance",
            name="gameweek",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_performances",
                to="kpl.gameweek",
            ),
        ),
        migrations.AddField(
            model_name="playerperformance",
            name="player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="performances",
                to="kpl.player",
            ),
        ),
        migrations.AlterField(
            model_name="fantasyplayer",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="kpl.player"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fantasyplayer",
            unique_together={("fantasy_team", "player")},
        ),
        migrations.AlterUniqueTogether(
            name="playerperformance",
            unique_together={("player", "gameweek")},
        ),
        migrations.RemoveField(
            model_name="fantasyplayer",
            name="gameweek",
        ),
        migrations.RemoveField(
            model_name="fantasyplayer",
            name="gameweek_points",
        ),
        migrations.RemoveField(
            model_name="playerperformance",
            name="fantasy_player",
        ),
        migrations.CreateModel(
            name="TeamSelection",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "formation",
                    models.CharField(
                        choices=[
                            ("3-4-3", "3-4-3"),
                            ("3-5-2", "3-5-2"),
                            ("4-4-2", "4-4-2"),
                            ("4-3-3", "4-3-3"),
                            ("5-3-2", "5-3-2"),
                            ("5-4-1", "5-4-1"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_finalized", models.BooleanField(default=False)),
                (
                    "captain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="captain_selections",
                        to="fantasy.fantasyplayer",
                    ),
                ),
                (
                    "fantasy_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selections",
                        to="fantasy.fantasyteam",
                    ),
                ),
                (
                    "gameweek",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_selections",
                        to="kpl.gameweek",
                    ),
                ),
                (
                    "starters",
                    models.ManyToManyField(
                        related_name="starter_selections", to="fantasy.fantasyplayer"
                    ),
                ),
                (
                    "vice_captain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vice_captain_selections",
                        to="fantasy.fantasyplayer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Selection",
                "verbose_name_plural": "Team Selections",
                "unique_together": {("fantasy_team", "gameweek")},
            },
        ),
    ]
