# Generated by Django 4.2.8 on 2025-08-06 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0003_alter_playerperformance_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fantasyteam",
            name="current_gameweek",
        ),
    ]
