# Generated by Django 4.2.8 on 2025-08-21 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kpl", "0013_alter_fixture_gameweek"),
        ("fantasy", "0004_remove_fantasyteam_current_gameweek"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fantasyplayer",
            name="gameweek_added",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="players_added",
                to="kpl.gameweek",
            ),
        ),
    ]
