# Generated by Django 4.2.8 on 2025-08-21 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kpl", "0013_alter_fixture_gameweek"),
        ("fantasy", "0005_alter_fantasyplayer_gameweek_added"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerperformance",
            name="gameweek",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="player_performances",
                to="kpl.gameweek",
            ),
        ),
        migrations.AlterField(
            model_name="playertransfer",
            name="gameweek",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="kpl.gameweek"
            ),
        ),
        migrations.AlterField(
            model_name="teamselection",
            name="gameweek",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="team_selections",
                to="kpl.gameweek",
            ),
        ),
    ]
