# Generated by Django 4.2.8 on 2025-08-21 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kpl", "0013_alter_fixture_gameweek"),
        ("fantasy", "0006_alter_playerperformance_gameweek_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fantasyplayer",
            name="gameweek_added",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players_added",
                to="kpl.gameweek",
            ),
        ),
        migrations.AlterField(
            model_name="playerperformance",
            name="gameweek",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_performances",
                to="kpl.gameweek",
            ),
        ),
        migrations.AlterField(
            model_name="playertransfer",
            name="gameweek",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="kpl.gameweek"
            ),
        ),
        migrations.AlterField(
            model_name="teamselection",
            name="gameweek",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_selections",
                to="kpl.gameweek",
            ),
        ),
    ]
