# Generated by Django 4.2.8 on 2025-08-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0007_alter_fantasyplayer_gameweek_added_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fantasyteam",
            name="formation",
            field=models.CharField(
                choices=[
                    ("3-4-3", "3-4-3"),
                    ("3-5-2", "3-5-2"),
                    ("4-4-2", "4-4-2"),
                    ("4-3-3", "4-3-3"),
                    ("5-3-2", "5-3-2"),
                    ("5-2-3", "5-2-3"),
                    ("5-4-1", "5-4-1"),
                ],
                default="3-4-3",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="teamselection",
            name="formation",
            field=models.CharField(
                choices=[
                    ("3-4-3", "3-4-3"),
                    ("3-5-2", "3-5-2"),
                    ("4-4-2", "4-4-2"),
                    ("4-3-3", "4-3-3"),
                    ("5-3-2", "5-3-2"),
                    ("5-2-3", "5-2-3"),
                    ("5-4-1", "5-4-1"),
                ],
                max_length=10,
            ),
        ),
    ]
