# Generated by Django 4.2.8 on 2025-09-10 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kpl", "0014_rename_is_relagated_team_is_relegated"),
        ("fantasy", "0008_alter_fantasyteam_formation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fantasyplayer",
            name="gameweek_added",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="players_added",
                to="kpl.gameweek",
            ),
        ),
        migrations.AlterField(
            model_name="playerperformance",
            name="gameweek",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="player_performances",
                to="kpl.gameweek",
            ),
        ),
        migrations.AlterField(
            model_name="playertransfer",
            name="gameweek",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="kpl.gameweek",
            ),
        ),
        migrations.AlterField(
            model_name="teamselection",
            name="captain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="captain_selections",
                to="fantasy.fantasyplayer",
            ),
        ),
        migrations.AlterField(
            model_name="teamselection",
            name="gameweek",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="team_selections",
                to="kpl.gameweek",
            ),
        ),
        migrations.AlterField(
            model_name="teamselection",
            name="vice_captain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vice_captain_selections",
                to="fantasy.fantasyplayer",
            ),
        ),
    ]
