# Generated by Django 4.2.8 on 2025-09-21 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kpl", "0016_externalfixturemapping_externalteammapping_and_more"),
        ("fantasy", "0009_alter_fantasyplayer_gameweek_added_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="playerperformance",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="playerperformance",
            name="fixture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="performances",
                to="kpl.fixture",
            ),
        ),
        migrations.AlterField(
            model_name="playerperformance",
            name="fantasy_points",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name="playerperformance",
            unique_together={("player", "fixture")},
        ),
    ]
