# Generated by Django 4.2.8 on 2025-10-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0010_alter_playerperformance_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamselection",
            name="bench",
            field=models.ManyToManyField(
                related_name="bench_selections", to="fantasy.fantasyplayer"
            ),
        ),
    ]
