# Generated by Django 4.2.8 on 2025-10-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0011_teamselection_bench"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fantasyteam",
            name="budget",
            field=models.DecimalField(decimal_places=2, default=70.0, max_digits=6),
        ),
    ]
