# Generated by Django 4.2.8 on 2025-11-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0012_alter_fantasyteam_budget"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="fantasyplayer",
            index=models.Index(
                fields=["fantasy_team", "is_starter"],
                name="fantasy_fan_fantasy_1297fb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fantasyplayer",
            index=models.Index(
                fields=["player", "fantasy_team"], name="fantasy_fan_player__85d458_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fantasyplayer",
            index=models.Index(
                fields=["is_captain"], name="fantasy_fan_is_capt_272fb5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fantasyplayer",
            index=models.Index(
                fields=["is_vice_captain"], name="fantasy_fan_is_vice_297c91_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playerperformance",
            index=models.Index(
                fields=["gameweek", "-fantasy_points"],
                name="fantasy_pla_gamewee_7d8c67_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="playerperformance",
            index=models.Index(
                fields=["player", "gameweek"], name="fantasy_pla_player__3e5b57_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playerperformance",
            index=models.Index(
                fields=["-goals_scored"], name="fantasy_pla_goals_s_1bd21b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playerperformance",
            index=models.Index(
                fields=["fixture"], name="fantasy_pla_fixture_5aa624_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamselection",
            index=models.Index(
                fields=["fantasy_team", "gameweek", "is_finalized"],
                name="fantasy_tea_fantasy_fa8903_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teamselection",
            index=models.Index(
                fields=["gameweek", "is_finalized"],
                name="fantasy_tea_gamewee_fa4c98_idx",
            ),
        ),
    ]
