# Generated by Django 4.2.8 on 2025-11-21 06:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("kpl", "0018_processedmatchevent_player_in_and_more"),
        ("fantasy", "0013_fantasyplayer_fantasy_fan_fantasy_1297fb_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chip",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chip_type",
                    models.CharField(
                        choices=[
                            ("TC", "Triple Captain"),
                            ("BB", "Bench Boost"),
                            ("WC", "Wildcard"),
                        ],
                        max_length=2,
                    ),
                ),
                ("is_used", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Chip",
                "verbose_name_plural": "Chips",
            },
        ),
        migrations.AddField(
            model_name="teamselection",
            name="active_chip",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TC", "Triple Captain"),
                    ("BB", "Bench Boost"),
                    ("WC", "Wildcard"),
                ],
                help_text="Active chip for this gameweek (if any)",
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="teamselection",
            index=models.Index(
                fields=["active_chip"], name="fantasy_tea_active__2bb14e_idx"
            ),
        ),
        migrations.AddField(
            model_name="chip",
            name="fantasy_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chips",
                to="fantasy.fantasyteam",
            ),
        ),
        migrations.AddField(
            model_name="chip",
            name="used_in_gameweek",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="chips_used",
                to="kpl.gameweek",
            ),
        ),
        migrations.AddIndex(
            model_name="chip",
            index=models.Index(
                fields=["fantasy_team", "chip_type"],
                name="fantasy_chi_fantasy_0bc1a8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chip",
            index=models.Index(
                fields=["is_used"], name="fantasy_chi_is_used_53f2cc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chip",
            unique_together={("fantasy_team", "chip_type")},
        ),
    ]
