# Generated by Django 4.2.8 on 2026-01-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0015_populate_chips_for_existing_teams"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="playertransfer",
            index=models.Index(
                fields=["fantasy_team", "gameweek"],
                name="fantasy_pla_fantasy_71a237_idx",
            ),
        ),
    ]
