# Generated by Django 4.2.8 on 2026-09-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0016_playertransfer_fantasy_pla_fantasy_71a237_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerperformance",
            name="bonus",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerperformance",
            name="bps",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerperformance",
            name="defensive_actions",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerperformance",
            name="goals_conceded",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerperformance",
            name="key_passes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="fantasyplayer",
            name="total_points",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="fantasyteam",
            name="total_points",
            field=models.IntegerField(default=0),
        ),
    ]
