# Generated by Django 4.2.8 on 2026-09-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0017_playerperformance_bonus_playerperformance_bps_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fantasyplayer",
            name="bench_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teamselection",
            name="points",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teamselection",
            name="points_calculated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teamselection",
            name="transfer_hit",
            field=models.IntegerField(default=0),
        ),
    ]
