# Generated by Django 4.2.8 on 2025-02-18 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("logo_url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "KPL Team",
                "verbose_name_plural": "KPL Teams",
            },
        ),
        migrations.CreateModel(
            name="Standing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("played", models.PositiveIntegerField()),
                ("wins", models.PositiveIntegerField()),
                ("draws", models.PositiveIntegerField()),
                ("losses", models.PositiveIntegerField()),
                ("goals_for", models.PositiveIntegerField()),
                ("goals_against", models.PositiveIntegerField()),
                ("goal_differential", models.IntegerField()),
                ("points", models.PositiveIntegerField()),
                ("period", models.CharField(max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standings",
                        to="kpl.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "KPL Standing",
                "verbose_name_plural": "KPL Standings",
                "ordering": ["position"],
            },
        ),
    ]
