# Generated by Django 4.2.8 on 2025-03-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kpl", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="standing",
            options={
                "ordering": ["position"],
                "verbose_name": "Standing",
                "verbose_name_plural": "Standings",
            },
        ),
        migrations.AlterModelOptions(
            name="team",
            options={
                "ordering": ["name"],
                "verbose_name": "Team",
                "verbose_name_plural": "Teams",
            },
        ),
        migrations.AlterField(
            model_name="fixture",
            name="away_team_score",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fixture",
            name="home_team_score",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="age",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="player",
            name="jersey_number",
            field=models.PositiveIntegerField(),
        ),
    ]
