# Generated by Django 4.2.8 on 2025-03-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kpl", "0002_alter_standing_options_alter_team_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="position",
            field=models.CharField(
                choices=[
                    ("GKP", "Goalkeeper"),
                    ("DEF", "Defender"),
                    ("MID", "Midfielder"),
                    ("FWD", "Foward"),
                ],
                max_length=50,
            ),
        ),
    ]
