# Generated by Django 4.2.8 on 2025-04-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kpl", "0003_alter_player_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fixture",
            name="status",
            field=models.CharField(
                choices=[
                    ("upcoming", "Upcoming"),
                    ("live", "Live"),
                    ("postponed", "Postponed"),
                    ("completed", "Completed"),
                ],
                default="Upcoming",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="jersey_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
