# Generated by Django 4.2.8 on 2025-04-02 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kpl", "0004_alter_fixture_status_alter_player_age_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="player",
            unique_together={("name", "team")},
        ),
    ]
