# Generated by Django 4.2.8 on 2025-04-05 21:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("kpl", "0005_alter_player_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gameweek",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveIntegerField(unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("transfer_deadline", models.DateTimeField()),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.AlterModelOptions(
            name="player",
            options={
                "ordering": ["team"],
                "verbose_name": "Player",
                "verbose_name_plural": "Players",
            },
        ),
        migrations.AlterUniqueTogether(
            name="player",
            unique_together=set(),
        ),
    ]
