# Generated by Django 4.2.8 on 2025-04-05 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kpl", "0006_gameweek_alter_player_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fixture",
            name="gameweek",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="kpl.gameweek",
            ),
        ),
    ]
