# Generated by Django 4.2.8 on 2025-04-25 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kpl", "0007_fixture_gameweek"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="fixture",
            unique_together={("home_team", "away_team", "match_date")},
        ),
    ]
