# Generated by Django 4.2.8 on 2025-05-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kpl", "0008_alter_fixture_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="position",
            field=models.CharField(
                choices=[
                    ("GKP", "Goalkeeper"),
                    ("DEF", "Defender"),
                    ("MID", "Midfielder"),
                    ("FWD", "Forward"),
                ],
                max_length=50,
            ),
        ),
    ]
