# Generated by Django 4.2.8 on 2025-06-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kpl", "0009_alter_player_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="jersey_image",
            field=models.ImageField(blank=True, null=True, upload_to="team_jerseys/"),
        ),
    ]
