# Generated by Django 4.2.8 on 2025-07-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kpl", "0010_team_jersey_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="current_value",
            field=models.DecimalField(decimal_places=2, default=4.0, max_digits=6),
        ),
    ]
