# Generated by Django 4.2.8 on 2025-08-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kpl", "0011_player_current_value"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gameweek",
            options={
                "ordering": ["number"],
                "verbose_name": "Gameweek",
                "verbose_name_plural": "Gameweeks",
            },
        ),
        migrations.AddField(
            model_name="team",
            name="is_relagated",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the team has been relegated from the league",
            ),
        ),
        migrations.AlterField(
            model_name="gameweek",
            name="number",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name="gameweek",
            unique_together={("number", "start_date")},
        ),
    ]
