# Generated by Django 4.2.8 on 2025-08-21 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kpl", "0012_alter_gameweek_options_team_is_relagated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fixture",
            name="gameweek",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="kpl.gameweek",
            ),
        ),
    ]
