# Generated by Django 4.2.8 on 2025-08-26 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kpl", "0013_alter_fixture_gameweek"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="is_relagated",
            new_name="is_relegated",
        ),
    ]
