# Generated by Django 4.2.8 on 2025-09-09 09:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("kpl", "0015_lineups_and_alias"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalFixtureMapping",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(max_length=50)),
                ("provider_fixture_id", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "External Fixture Mapping",
                "verbose_name_plural": "External Fixture Mappings",
            },
        ),
        migrations.CreateModel(
            name="ExternalTeamMapping",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(max_length=50)),
                ("provider_team_id", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "External Team Mapping",
                "verbose_name_plural": "External Team Mappings",
            },
        ),
        migrations.RenameIndex(
            model_name="playeralias",
            new_name="kpl_playera_team_id_9a7a2c_idx",
            old_name="kpl_player_alias_team_norm_idx",
        ),
        migrations.AddField(
            model_name="externalteammapping",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="external_ids",
                to="kpl.team",
            ),
        ),
        migrations.AddField(
            model_name="externalfixturemapping",
            name="fixture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="external_ids",
                to="kpl.fixture",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="externalteammapping",
            unique_together={("provider", "provider_team_id")},
        ),
        migrations.AlterUniqueTogether(
            name="externalfixturemapping",
            unique_together={("provider", "provider_fixture_id")},
        ),
    ]
