# Generated by Django 4.2.8 on 2025-10-25 13:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("kpl", "0016_externalfixturemapping_externalteammapping_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessedMatchEvent",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(max_length=50)),
                ("event_key", models.CharField(max_length=255)),
                ("minute", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fixture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="kpl.fixture"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="kpl.player"
                    ),
                ),
            ],
            options={
                "unique_together": {("fixture", "event_key")},
            },
        ),
    ]
