# Generated by Django 4.2.8 on 2025-10-26 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kpl", "0017_processedmatchevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="processedmatchevent",
            name="player_in",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="substitutions_in",
                to="kpl.player",
            ),
        ),
        migrations.AddField(
            model_name="processedmatchevent",
            name="player_out",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="substitutions_out",
                to="kpl.player",
            ),
        ),
        migrations.AlterField(
            model_name="processedmatchevent",
            name="player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="kpl.player",
            ),
        ),
        migrations.AddIndex(
            model_name="processedmatchevent",
            index=models.Index(
                fields=["fixture", "event_type"], name="kpl_process_fixture_c1675d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="processedmatchevent",
            index=models.Index(
                fields=["event_key"], name="kpl_process_event_k_7cd6c9_idx"
            ),
        ),
    ]
