# Generated by Django 4.2.8 on 2025-12-03 07:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("kpl", "0018_processedmatchevent_player_in_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopcorerData",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("player_name", models.CharField(max_length=200)),
                ("team_name", models.CharField(max_length=200)),
                ("goals", models.PositiveIntegerField()),
                ("rank", models.PositiveIntegerField()),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gameweek",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_scorers",
                        to="kpl.gameweek",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_scorer_records",
                        to="kpl.player",
                    ),
                ),
            ],
            options={
                "verbose_name": "Top Scorer Data",
                "verbose_name_plural": "Top Scorer Data",
                "ordering": ["gameweek", "rank"],
                "unique_together": {("gameweek", "player_name")},
            },
        ),
    ]
