# Generated by Django 4.2.8 on 2026-09-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kpl", "0019_topcorerdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="logo_image",
            field=models.ImageField(blank=True, null=True, upload_to="team_logos/"),
        ),
    ]
