# Generated by Django 4.2.8 on 2026-09-05 18:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("kpl", "0020_team_logo_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalPlayerMapping",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(max_length=50)),
                ("provider_player_id", models.CharField(max_length=100)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_ids",
                        to="kpl.player",
                    ),
                ),
            ],
            options={
                "verbose_name": "External Player Mapping",
                "verbose_name_plural": "External Player Mappings",
                "indexes": [
                    models.Index(
                        fields=["provider", "provider_player_id"],
                        name="kpl_externa_provide_2e348d_idx",
                    )
                ],
                "unique_together": {("provider", "provider_player_id")},
            },
        ),
    ]
